server:
  port: 8082
spring:
  application:
    name: mservice-provider
info:
  app.name: mservice-provider
  owner: jadezhang
  build.artifactId: $project.artifactId$
  build.version: $project.version$
eureka:
  instance:
    instance-id: mservice-provider
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
      ff: 航阿迪发动时