spring:
  profile:
    active:
    - dev
---
spring:
  profile: dev
  application:
    name: mservice-provider-dev
foo: dev-foo version 1.0

---
spring:
   profile: test
   application:
    name: mservice-provider-test